name: Genereate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5.0.0
      - name: Run Feed Generator
        uses: eecourt/podcast-generator@main
